services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80" # Фронтенд доступен на порту 8080
    networks:
      - app_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000" # Бэкенд доступен на порту 8000
    env_file:
      - ./backend/.env
    depends_on:
      - database
    networks:
      - app_network

  database:
    image: postgres:15
    container_name: database
    ports:
      - "5432:5432" # База данных PostgreSQL доступна на порту 8010
    env_file:
      - ./database/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge

