apiVersion: v1
kind: Service
metadata:
  name: traefik-dashboard-service
  namespace: coursework

spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: dashboard
  selector:
    app: traefik
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-backend-service
  namespace: coursework

spec:
  type: LoadBalancer
  ports:
    - port: 8008
      targetPort: backend
  selector:
    app: traefik
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-web-service
  namespace: coursework

spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: web
  selector:
    app: traefik