apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc
  namespace: coursework
spec:
  volumeName: database-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi