apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: coursework
spec:
  selector:
    app: database
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
