name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Запускать на изменения в ветке main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Backend Docker Image
        run: |
          docker build -t kerrodar/coursework-springboot-backend:latest ./backend
          docker push kerrodar/coursework-springboot-backend:latest

      - name: Build and Push Frontend Docker Image
        run: |
          docker build -t kerrodar/coursework-nginx-frontend:latest ./frontend
          docker push kerrodar/coursework-nginx-frontend:latest


  deploy:
    runs-on: self-hosted
    needs: build # Этот шаг зависит от завершения job build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Verify kubectl version
        run: kubectl version --client

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/backend-deployment backend=kerrodar/coursework-springboot-backend:latest
          kubectl rollout restart deployment/backend-deployment
          kubectl set image deployment/frontend-deployment frontend=kerrodar/coursework-nginx-frontend:latest
          kubectl rollout restart deployment/frontend-deployment
